version: '3.5'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4576:4576" #sqs
    environment:
      - "SERVICES=sqs"
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
